CREATE TABLE user(
    ID VARCHAR(36) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    DELETED_AT DATETIME NULL
);
